### ISSUE TITLE
Update to use a custom icon for the config files

### ISSUE THREAD

**Issue by nrayburn-tech** [oxc-project/oxc-intellij-plugin#61]
All of the oxlint config files should be updated to use a custom icon.  There is some guidance on how to do this available here https://plugins.jetbrains.com/docs/intellij/icons.html.

1. Identify the required icon files
2. Add the icon files to the resources/icons folder
3. Create an "icon holder" class that loads all the icons
4. Create an IconProvider to load the appropriate icon based on the file. (Determine what to do with eslint config files)
5. Register the IconProvider within plugin.xml

**Comment by nrayburn-tech** [comment]
@IWANABETHATGUY any idea where I might be able to get the SVG files for this?  https://plugins.jetbrains.com/docs/intellij/icons-style.html contains the guidelines for the icons.  I've also put the stylelint SVG files below for reference.  We only need the dark versions if the dark icon should be different than the light version.

![stylelint-dark](https://github.com/user-attachments/assets/1136120d-a6d0-4e96-a5fc-936167767c5d) dark
![stylelint](https://github.com/user-attachments/assets/decc6ead-efe0-4d44-b217-e267d2e353a9) light
![new-styleline-dark](https://github.com/user-attachments/assets/9fe01f11-129a-49e5-8957-8a6bdf46cc25) new ui dark
![new-stylelint](https://github.com/user-attachments/assets/6bf700fe-54a0-47d5-9806-1c8e14768734) new ui light

**Comment by DonIsaac** [comment]
I made a PR into vscode-icons adding our round SVG icon. We can also add it as a file icon theme in our own extension if we want, but I think this is a better solution.

https://github.com/vscode-icons/vscode-icons/pull/3604
